const mongoose = require('mongoose');

const workSessionSchema = new mongoose.Schema(
  {
    // ================= BASIC SESSION INFO =================
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true
    },

    sessionStart: {
      type: Date,
      required: true
    },

    sessionEnd: {
      type: Date
    },

    status: {
      type: String,
      enum: ['running', 'completed'],
      default: 'running'
    },

    // ================= ML EFFICIENCY SCORES =================
    typingEfficiency: {
      type: Number,
      default: 100
    },

    mouseEfficiency: {
      type: Number,
      default: 100
    },

    faceEfficiency: {
      type: Number,
      default: 100
    },

    screenEfficiency: {
      type: Number,
      default: 100
    },

    overallEfficiency: {
      type: Number,
      default: 100
    },

    // ================= EVIDENCE PATHS =================
    // These store FILE PATHS of proofs generated by ML modules
    evidence: {
      face: {
        type: [String],
        default: []
      },
      typing: {
        type: [String],
        default: []
      },
      screen: {
        type: [String],
        default: []
      }
    }
  },
  {
    timestamps: true
  }
);

module.exports = mongoose.model('WorkSession', workSessionSchema);
